### ISSUE TITLE
Undocumented options -o -l

### ISSUE THREAD

**Issue by andreamtp** [antonioromito/rhsm-api-client#1]
In the README are reported as example the usage of options _-o_ and _-l_ :

-o /path/to/systems.csv -l 100

but neither the help inline or the documentation report the expected behaviour of those

**Comment by antonioromito** [comment]
Hi Andrea, the cli helper related to "systems" positional argument, give more details about the "-o" and "-l", but thanks for reporting this.

```
rhsm-api-client > ./rhsm-cli systems -h
usage: rhsm-cli systems [-h] -o OUTPUT_CSV [-l LIMIT]

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT_CSV, --output_csv OUTPUT_CSV
                        Output CSV file
  -l LIMIT, --limit LIMIT
                        The default and max number of result in a response are
                        100.
```
Does this answer provide the solution to this issue?

**Comment by antonioromito** [comment]
Added helper for systems arguments also in the documentation.

**Comment by antonioromito** [comment]
@all-contributors please add @andreamtp for his userTesting
