### ISSUE TITLE
Cannot download offline Maven repository from access.redhat.com

### ISSUE THREAD

**Issue by jiridanek** [antonioromito/rhsm-api-client#8]
I wanted to download the file `AMQ-CLIENTS-2.6.0/amq-jms-2.6.0-maven-repository.zip`. I was able to find it on the access.redhat.com web page, at https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=78541&product=jboss.amq.clients&version=2.6.0&downloadType=distributions, but I was not able to figure out how to download it using this API.

Can you explain how I can use the client to accomplish that?

**Comment by antonioromito** [comment]
Hello @jiridanek sorry for the late answer here.

Reading the API documentation I see that for the images endpoint download option it's meant for:

`Download an image by its SHA256 checksum

Find an image by its SHA256 checksum and generate a download link with a short-lived expiration. It is expected for users to obtain a new download link every time an image is downloaded and to not store the link for more than several minutes. If the user has "Download Software and Updates" permissions and a valid subscription for the image, they will receive a HTTP 307 redirect to the location on the Red Hat CDN. Clients can either follow the HTTP redirect or find the download URL in the response body.
`

I believe that what are you trying to download it's not an "image" but more a "package". I've to dig into this to understand if it's possible to download it via API or not.

**Comment by jiridanek** [comment]
I've resolved this in the meantime by parsing the html page with BeautifulSoup and getting the links that way.

**Comment by antonioromito** [comment]
@jiridanek I've asked internally and I can confirm that unfortunately the package you are asking for cannot be downloaded via RHSM API. I'm going to close this one.
