### ISSUE TITLE
when subscriptions options is used it download only partial list

### ISSUE THREAD

**Issue by antonioromito** [antonioromito/rhsm-api-client#9]

**Comment by sujan46** [comment]
+1
When try to generate report  with CSV format only 50 entries where it has 190 entries in my redhat account.

`[xx@xx.xx.xx.xx]# rhsm-cli subscriptions -f csv > /tmp/test.csv`
`[xx@xx.xx.xx.xx]# wc -l /tmp/test.csv`
`51 /tmp/test.csv`

**Comment by antonioromito** [comment]
Fixed with the last commit on master
